### PR TITLE
Refactor scss and refresh base UI

### PR DESCRIPTION
**Pull request by stevescavo**
- Import fonts first and foremost
- Rename `base` partial to `root.scss`
- "Layouts" partial is now responsible for importing specific layout components, as well as common layout classes, i.e. `.container`
- Break out "links" from "typography" so it's more inline with the W3C category and spec
- Build out a mobile-first UI (this was grating on my soul)
- Prefer `em` over `rem` units
- Cleanup, revise and prune comments
- Update normalize.css to v3.0.3

### CODE REVIEW

**Comment by claus** [comment]
> Prefer `em` over `rem` units
Why?

**Comment by stevescavo** [comment]
In general, I like using `em` units, especially for `font-size`, because of the way they inherit from their direct or nearest parent. Controlling the style of a specific component in relation to the ratios already established within the app feels right to me. It can save you from redefining the same properties over and over again. 

Targeting components using a `rem` value each time feels too much like a "reset" due to the fact that `rem` units are relative only to the document root. `em` units promote (and literally allow for) inheritance, and what I think is the proper mindset when writing css.

However, if a page or application has a hardline requirement for consistent layout spacing regardless of `font-size` changes (i.e. `margin`, `padding`, etc), I do feel that `rem` would be a good choice for the reasons mentioned above.

**Comment by claus** [comment]
Yes everything you mentioned makes sense and is indeed very elegant _in theory_. When it comes to practice though, inherited sizes are more often than not quite a pain to work with. For the average project we don't have sophisticated style guides (that are written in stone) where those inheritance rules are cleanly specced out. Usually we work from quite flat PSDs where sizes are absolute. Usually sizes don't just scale uniformly between breakpoints. And regularly we get requests like "can you make the H2 headline on tablets a bit bigger please". All that makes working with `em` problematic i think, and that's why i generally favour `rem` (with a few exceptions of course, like `letter-spacing`, where `em` makes actually sense).

**Comment by stevescavo** [comment]
Maybe I'm masochistic, but I believe we should plan as if the app we're building abides by sound design principles, and the designer appreciates _and embraces_ a fluid digital canvas. If there are deviations and/or poor design decisions along the way – of course, we can account for those – but I think our starter should be inline with our optimal setup. :nail_care:

**Comment by stevescavo** [comment]
More than happy to tweak as needed.

@sambernard @rynocouse @rafacv @stigmergic @bribeiro – any thoughts? Love it? Hate it? Close it? Merge it?

**Comment by stevescavo** [comment]
sounds-good-peter-3050o3

**Comment by claus** [comment]
@stevescavo doooo eeeeeeet!

**Pull request merged**
